# Generated by Django 4.2.5 on 2023-10-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_remove_members_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='otp',
        ),
    ]
