# Generated by Django 4.2.5 on 2023-10-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_members_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='otp',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='members',
            name='password',
        ),
    ]
