# Generated by Django 4.2.5 on 2023-10-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_rename_otp_members_code_remove_members_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
