# Generated by Django 4.2.5 on 2023-10-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_alter_members_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ymail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100)),
                ('msg', models.TextField()),
            ],
        ),
    ]
